config/routes.rb
Rails.application.routes.draw do
  resources :locations

  resources :vm_problems, :users

  get '/tickets/open' => 'tickets#open'
  get '/tickets/closed' => 'tickets#closed'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  resources :tickets
  
  root 'home#index'
end

app/models/vm_problem.rb
class VmProblem < ActiveRecord::Base
end

app/controllers/vm_problems_controller.rb
class VmProblemsController < ApplicationController
  before_action :set_vm_problem, only: [:show, :edit, :update, :destroy]

  #Check for admin rights
  before_action :check_for_admin, only: [:edit, :update, :destroy, :index]

  # GET /vm_problems
  # GET /vm_problems.json
  def index
    @vm_problems = VmProblem.all
  end

  # GET /vm_problems/1
  # GET /vm_problems/1.json
  def show
  end

  # GET /vm_problems/new
  def new
    @vm_problem = VmProblem.new
  end

  # GET /vm_problems/1/edit
  def edit
  end

  # POST /vm_problems
  # POST /vm_problems.json
  def create
    @vm_problem = VmProblem.new(vm_problem_params)

    respond_to do |format|
      if @vm_problem.save
        format.html { redirect_to root_path, notice: 'Vm problem was successfully created.' }
        format.json { render :show, status: :created, location: @vm_problem }
      else
        format.html { render :new }
        format.json { render json: @vm_problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vm_problems/1
  # PATCH/PUT /vm_problems/1.json
  def update
    respond_to do |format|
      if @vm_problem.update(vm_problem_params)
        format.html { redirect_to @vm_problem, notice: 'Vm problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @vm_problem }
      else
        format.html { render :edit }
        format.json { render json: @vm_problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vm_problems/1
  # DELETE /vm_problems/1.json
  def destroy
    @vm_problem.destroy
    respond_to do |format|
      format.html { redirect_to vm_problems_url, notice: 'Vm problem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vm_problem
      @vm_problem = VmProblem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vm_problem_params
      params.require(:vm_problem).permit(:who_are_you, :what_is_the_problem, :resolved)
    end

    def check_for_admin
      if !current_user.admin
        redirect_to root_path
      end
    end
end

app/helpers/vm_problems_helper.rb
module VmProblemsHelper
end

app/views/vm_problems/_form.html.haml
= simple_form_for(@vm_problem) do |f|
  = f.error_notification
  = f.input :who_are_you, :label => "What is your virtual login name (i.e. bww01)"
  = f.input :what_is_the_problem
  = f.button :submit, "Report"

app/views/vm_problems/edit.html.haml
.container.well
	.col-md-6
		%h1 Editing VM Problem
		= simple_form_for(@vm_problem) do |f|
			= f.error_notification
			= f.input :who_are_you
			= f.input :what_is_the_problem
			= f.input :resolved
			= f.button :submit, "Update Problem"

app/views/vm_problems/index.html.haml
.container.well
  .col-md-6
    %h1 Listing VM Problems
    %table.table.table-striped
      %tr
        %th User with issue
        %th Problem
        %th Resolved?
        %th{:colspan => "3"}
      
      - @vm_problems.each do |vm_problem|
        %tr
          %td= vm_problem.who_are_you
          %td= vm_problem.what_is_the_problem
          %td
            -if vm_problem.resolved
              yes
            -else
              no
          %td= link_to 'Show', vm_problem, :class => "btn btn-sm btn-default"
          %td= link_to 'Edit', edit_vm_problem_path(vm_problem), :class => "btn btn-sm btn-default"
          %td= link_to 'Destroy', vm_problem, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger'

app/views/vm_problems/new.html.haml
.container.well
	.col-md-6

		%h1 Report a VM Problem
		%h4 If this is something urgent please call Sean at 661-865-0133
		%h5 Urgent items include, but are not limited to:
		%ul
			%li Inability to print
			%li Inability to access Agvance
			%li Agvance Accounting or Blending not working
			%li Black screen when logging in
		= render 'form'

app/views/vm_problems/show.html.haml
%p#notice= notice
%p
  %strong Who are you:
  = @vm_problem.who_are_you
%p
  %strong What is the problem:
  = @vm_problem.what_is_the_problem
%p
  %strong Resolved:
  = @vm_problem.resolved
= link_to 'Edit', edit_vm_problem_path(@vm_problem)
|
= link_to 'Back', vm_problems_path