config/routes.rb
Rails.application.routes.draw do
  resources :locations

  resources :vm_problems, :users

  get '/tickets/open' => 'tickets#open'
  get '/tickets/closed' => 'tickets#closed'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  resources :tickets
  
  root 'home#index'
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :check_for_admin, only: [:index, :show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  def open
    @tickets = Ticket.where("date_resolved IS NULL")
  end

  def closed
    @tickets = Ticket.where("date_resolved IS NOT NULL")
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create 
    temp_ticket_params = ticket_params
    temp_ticket_params[:date_submitted] ? temp_ticket_params[:date_submitted] = temp_ticket_params[:date_submitted].to_s() : nil
    temp_ticket_params[:date_occurred] ? temp_ticket_params[:date_occurred] = temp_ticket_params[:date_occurred].to_s() : nil

    @ticket = Ticket.new(temp_ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to root_path, notice: 'Ticket was successfully created.' }
        #format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    temp_ticket_params = ticket_params
    temp_ticket_params[:date_submitted].present? ? temp_ticket_params[:date_submitted] = temp_ticket_params[:date_submitted].to_s() : nil
    temp_ticket_params[:date_occurred] ? temp_ticket_params[:date_occurred] = temp_ticket_params[:date_occurred].to_s() : nil
    temp_ticket_params[:date_resolved] ? temp_ticket_params[:date_resolved] = temp_ticket_params[:date_resolved].to_s() : nil
    
    respond_to do |format|
      if @ticket.update(temp_ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:date_submitted, :date_occurred, :affected_user, :problem_description, :date_resolved, :problem_resolution)
    end

    def check_for_admin
      if !current_user.admin
        redirect_to root_path
      end
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= simple_form_for @ticket do |f| %>
  <%= f.error_notification %>
  <div class="col-md-6">
    <%= f.input :date_submitted, :as => :hidden, input_html: { value: Time.now } %>
    <%= f.input :date_occurred, :label => false, :as => :datetime_picker, :placeholder => "Date problem started" %>
    <%= f.input :affected_user, :label => false, :placeholder => "Affected user" %>
    <%= f.input :problem_description, :label => false, :placeholder => "Description of the problem" %>
    <%= f.input :date_resolved, :as => :datetime_picker %>
	  <%= f.input :problem_resolution %>
    
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tickets/closed.html.haml
.container.well
  %h1 Closed Trouble Tickets
  %table.table.table-striped
    %thead
      %tr
        %th Date submitted
        %th Date occurred
        %th Affected user
        %th Date resolved
        %th{:colspan => "1"}
    %tbody
      - @tickets.order("date_submitted").each do |ticket|
        %tr.success
          %td= ticket.date_submitted.try(:strftime, "%a, %b %d %Y %l:%M %p")
          %td= ticket.date_occurred.try(:strftime, "%a, %b %d %Y %l:%M %p")
          %td= ticket.affected_user
          %td= ticket.date_resolved.try(:strftime, "%a, %b %d %Y %l:%M %p")
          %td= link_to 'Show', ticket, :class => 'btn btn-sm btn-default'
          %td= link_to 'Edit', edit_ticket_path(ticket), :class => 'btn btn-sm btn-default'
          %td= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'hidden btn btn-sm btn-danger'
  %br/
  = link_to 'New Ticket', new_ticket_path, :class => "btn btn-default"

app/views/tickets/edit.html.erb
<div class="container well">
	<h1>Editing Ticket</h1>

	<%= simple_form_for @ticket do |f| %>
	  <%= f.error_notification %>
	  <div class="col-md-6">
	    <%= f.input :date_submitted, :as => :datetime_picker %>
	    <%= f.input :date_occurred, :as => :datetime_picker %>
	    <%= f.input :affected_user %>
	    <%= f.input :problem_description %>
	    <%= f.input :date_resolved, :as => :datetime_picker %>
	    <%= f.input :problem_resolution %>
	    
	    <%= f.button :submit %>
	  </div>
	<% end %>
</div>

app/views/tickets/index.html.erb
<div class="container well">
  <h1>All Trouble Tickets</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date submitted</th>
        <th>Date occurred</th>
        <th>Affected user</th>
        <th>Date resolved</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.order("date_submitted").each do |ticket| %>
        <% if ticket.date_resolved.present? %>
          <tr class="success">
        <% else %>
          <tr class="danger">
        <% end %>
          <td><%= ticket.date_submitted.try(:strftime, "%a, %b %d %Y %l:%M %p") %></td>
          <td><%= ticket.date_occurred.try(:strftime, "%a, %b %d %Y %l:%M %p") %></td>
          <td><%= ticket.affected_user %></td>
          <td><%= ticket.date_resolved.try(:strftime, "%a, %b %d %Y %l:%M %p") %></td>
          <td><%= link_to 'Show', ticket, :class => 'btn btn-sm btn-default' %></td>
          <td><%= link_to 'Edit', edit_ticket_path(ticket), :class => 'btn btn-sm btn-default' %></td>
          <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'hidden btn btn-sm btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Ticket', new_ticket_path, :class => "btn btn-default" %>
</div>

app/views/tickets/new.html.erb
<div class="container well">
	<h1>New Trouble Ticket</h1>
	<%= render 'form' %>
</div>

app/views/tickets/open.html.haml
.container.well
  %h1 Open Trouble Tickets
  %table.table.table-striped
    %thead
      %tr
        %th Date submitted
        %th Date occurred
        %th Affected user
        %th Date resolved
        %th{:colspan => "1"}
    %tbody
      - @tickets.order("date_submitted").each do |ticket|
        %tr.danger
          %td= ticket.date_submitted.try(:strftime, "%a, %b %d %Y %l:%M %p")
          %td= ticket.date_occurred.try(:strftime, "%a, %b %d %Y %l:%M %p")
          %td= ticket.affected_user
          %td= ticket.date_resolved.try(:strftime, "%a, %b %d %Y %l:%M %p")
          %td= link_to 'Show', ticket, :class => 'btn btn-sm btn-default'
          %td= link_to 'Edit', edit_ticket_path(ticket), :class => 'btn btn-sm btn-default'
          %td= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'hidden btn btn-sm btn-danger'
            
  %br/
  = link_to 'New Ticket', new_ticket_path, :class => "btn btn-default"

app/views/tickets/show.html.haml
.container.well
	%h3 Ticket for #{@ticket.affected_user}
	%table.table
		%tr
			%td	Date Submitted
			%td #{@ticket.date_submitted}
		%tr
			%td Date Occurred
			%td #{@ticket.date_occurred}
		%tr
			%td Affected User
			%td #{@ticket.affected_user}
		%tr
			%td Problem Description
			%td #{@ticket.problem_description}
		%tr
			%td Date Resolved
			%td #{@ticket.date_resolved}
		%tr
			%td Problem Resolution
			%td #{@ticket.problem_resolution}

	= link_to 'Back', tickets_path, :class => "btn btn-default"