config/routes.rb
Rails.application.routes.draw do
  resources :locations

  resources :vm_problems, :users

  get '/tickets/open' => 'tickets#open'
  get '/tickets/closed' => 'tickets#closed'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  resources :tickets
  
  root 'home#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title IT Ticket Tracker
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/"}
            = image_tag 'bwc-logo.png', :class => "fiddy"
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                IT Support
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li= link_to "New Ticket", new_ticket_path
                %li= link_to "Report VM Problem", new_vm_problem_path
                - if current_user
                  - if current_user.admin?
                    %li.divider
                    %li= link_to "All Tickets", tickets_path
                    %li= link_to "Open Tickets", tickets_open_path
                    %li= link_to "Closed Tickets", tickets_closed_path
                    %li.divider
                    %li= link_to "VM Problems", vm_problems_path
            - if current_user
              - if current_user.admin?
                %li.dropdown
                  %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                    User Admin
                    %span.caret
                  %ul.dropdown-menu{:role => "menu"}                    
                    %li= link_to "All Users", users_path
                    %li= link_to "New User", new_user_path
            %li= link_to "Locations", locations_path
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li= link_to "Logged in as #{current_user.email}", edit_user_path(current_user.id)
              %li= link_to "Logout", log_out_path
            - else
              %li= link_to "Sign up", new_user_path
              %li= link_to "Login", log_in_path

    - if notice
      %p.alert.alert-success= notice
    - if alert
      %p.alert.alert-danger= alert
    = yield